# Generated by Django 2.1.5 on 2019-02-06 06:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0002_pricepolicy'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pricepolicy',
            old_name='table_name',
            new_name='content_type',
        ),
    ]
